const qs = @import("../../lib/quantity_spec.zig");
const base = @import("base.zig");
const st = @import("space_and_time.zig");
const si = @import("si_quantities.zig");
const mc = @import("mechanics.zig");

pub const ElectricCharge = qs.DerivedQuantitySpec("electric charge", base.ElectricCurrent.Times(base.Time));
pub const ElementaryCharge = qs.ChildQuantitySpec("elementary charge", ElectricCharge);
pub const ElectricChargeDensity = qs.DerivedQuantitySpec("electric charge density", ElectricCharge.Div(st.Volume));
pub const VolumeElectricCharge = ElectricChargeDensity;
pub const VolumicCharge = ElectricChargeDensity;
pub const SurfaceDensityOfElectricCharge = qs.DerivedQuantitySpec("surface density of electric charge", ElectricCharge.Div(si.Area));
pub const AreicElectricCharge = SurfaceDensityOfElectricCharge;
pub const AreicCharge = SurfaceDensityOfElectricCharge;
pub const LinearDensityOfElectricCharge = qs.DerivedQuantitySpec("linear density of electric charge", ElectricCharge.Div(base.Length));
pub const LineicElectricCharge = LinearDensityOfElectricCharge;
pub const LineicCharge = LinearDensityOfElectricCharge;
pub const ElectricDipoleMoment = qs.DerivedQuantitySpec("electric dipole moment", ElectricCharge.Times(st.Displacement)); // TODO verify is vector
pub const ElectricPolarization = qs.DerivedQuantitySpec("electric polarization", ElectricDipoleMoment.Div(st.Volume)); // TODO verify is vector
pub const ElectricCurrentDensity = qs.DerivedQuantitySpec("electric current density", ElectricChargeDensity.Times(st.Velocity)); // TODO verify is vector
pub const LinearElectricCurrentDensity = qs.DerivedQuantitySpec("linear electric current density", SurfaceDensityOfElectricCharge.Times(st.Velocity)); // TODO verify is vector
pub const ElectricFieldStrength = qs.DerivedQuantitySpec("electric field strength", mc.Force.Div(ElectricCharge)); // TODO verify is vector
pub const ElectricPotential = qs.DerivedQuantitySpecOfCharacter("electric potential", ElectricFieldStrength.Times(base.Length), qs.QuantityCharacter.scalar); // TODO from mp-units what is a correct equation here?
pub const ElectricPotentialDifference = qs.DerivedQuantitySpecOfCharacter("electric potential difference", ElectricPotential, qs.QuantityCharacter.scalar);
pub const Voltage = qs.ChildQuantitySpec("voltage", ElectricPotential);
pub const ElectricTension = Voltage;
pub const InducedVoltage = qs.ChildQuantitySpec("induced voltage", Voltage); // TODO from mp-units what is a correct equation here?
pub const ElectricFluxDensity = qs.ChildQuantitySpec("electric flux density", ElectricPolarization); // TODO verify is vector
pub const ElectricDisplacement = ElectricFluxDensity;
pub const Capacitance = qs.DerivedQuantitySpec("capacitance", ElectricCharge.Div(Voltage));
pub const MagneticFluxDensity = qs.DerivedQuantitySpecOfCharacter("magnetic flux density", mc.Force.Div(ElectricCharge.Times(st.Velocity)), qs.QuantityCharacter.vector); // TODO from mp-units how to calculate an argument of a vector product?
pub const MagneticConstant = qs.DerivedQuantitySpec("magnetic constant", ElectricPotential.Times(base.Time).DivEqn(base.ElectricCurrent.Times(base.Length))); // TODO from mp-units what is a correct equation here?
pub const PermeabilityOfVacuum = MagneticConstant;
pub const PhaseSpeedOfElectromagneticWaves = qs.DerivedQuantitySpec("phase speed of electromagnetic waves", st.AngularFrequency.Div(st.AngularWavenumber));
pub const SpeedOfLightInVacuum = qs.ChildQuantitySpec("speed of light in vacuum", st.Speed);
pub const LightSpeedInVacuum = SpeedOfLightInVacuum;
pub const LuminalSpeed = SpeedOfLightInVacuum;
pub const ElectricConstant = qs.DerivedQuantitySpec("electric constant", MagneticConstant.TimesEqn(SpeedOfLightInVacuum.Pow(2)).Inverse());
pub const PermittivityOfVacuum = ElectricConstant;
pub const Permittivity = qs.DerivedQuantitySpecOfCharacter("permittivity", ElectricFluxDensity.Div(ElectricFieldStrength), qs.QuantityCharacter.scalar);
pub const RelativePermittivity = qs.ChildQuantitySpecWithEquation("relative permittivity", qs.Dimensionless, Permittivity.Div(ElectricConstant));
pub const ElectricSusceptibility = qs.ChildQuantitySpecWithEquationOfCharacter("electric susceptibility", qs.Dimensionless, ElectricPolarization.Div(ElectricConstant).Div(ElectricFieldStrength), qs.QuantityCharacter.scalar);
pub const ElectricFlux = qs.DerivedQuantitySpecOfCharacter("electric flux", ElectricFluxDensity.Times(si.Area), qs.QuantityCharacter.scalar);
pub const DisplacementCurrentDensity = qs.DerivedQuantitySpec("displacement current density", ElectricFluxDensity.Div(base.Time)); // TODO verify is vector
pub const DisplacementCurrent = qs.ChildQuantitySpecWithEquationOfCharacter("displacement current", base.ElectricCurrent, DisplacementCurrentDensity.Times(si.Area), qs.QuantityCharacter.scalar);
pub const TotalCurrent = qs.ChildQuantitySpec("total current", base.ElectricCurrent);
pub const TotalCurrentDensity = qs.ChildQuantitySpec("total current density", ElectricCurrentDensity); // TODO verify is vector
pub const MagneticFlux = qs.DerivedQuantitySpecOfCharacter("magnetic flux", MagneticFluxDensity.Times(si.Area), qs.QuantityCharacter.scalar);
pub const MagneticVectorPotential = qs.DerivedQuantitySpec("magnetic vector potential", MagneticFluxDensity.Times(base.Length)); // TODO verify is vector  // TODO from mp-units what is a correct equation here?
pub const Protoflux = qs.DerivedQuantitySpecOfCharacter("protoflux", MagneticVectorPotential.Times(st.Displacement), qs.QuantityCharacter.scalar);
pub const LinkedMagneticFlux = qs.ChildQuantitySpec("linked magnetic flux", MagneticFlux);
pub const TotalMagneticFlux = qs.ChildQuantitySpec("total magnetic flux", MagneticFlux);
pub const MagneticMoment = qs.DerivedQuantitySpecOfCharacter("magnetic moment", base.ElectricCurrent.Times(si.Area), qs.QuantityCharacter.vector);
pub const MagneticAreaMoment = MagneticMoment;
pub const Magnetization = qs.DerivedQuantitySpec("magnetization", MagneticMoment.Div(st.Volume)); // TODO verify is vector
pub const MagneticFieldStrength = qs.ChildQuantitySpec("magnetic field strength", Magnetization); // TODO verify is vector
pub const MagnetizingField = MagneticFieldStrength;
pub const Permeability = qs.DerivedQuantitySpecOfCharacter("permeability", MagneticFluxDensity.Div(MagneticFieldStrength), qs.QuantityCharacter.scalar);
pub const RelativePermeability = qs.ChildQuantitySpecWithEquation("relative permeability", qs.Dimensionless, Permeability.Div(MagneticConstant));
pub const MagneticSusceptibility = qs.ChildQuantitySpecWithEquationOfCharacter("magnetic susceptibility", qs.Dimensionless, Magnetization.Div(MagneticFieldStrength), qs.QuantityCharacter.scalar);
pub const MagneticPolarization = qs.DerivedQuantitySpec("magnetic polarization", MagneticConstant.Times(Magnetization)); // TODO verify is vector
pub const MagneticDipoleMoment = qs.DerivedQuantitySpec("magnetic dipole moment", MagneticConstant.Times(MagneticMoment)); // TODO verify is vector
pub const Coercivity = qs.ChildQuantitySpecOfCharacter("coercivity", MagneticFieldStrength, qs.QuantityCharacter.scalar);
pub const CoerciveFieldStrength = Coercivity;
pub const ElectromagneticEnergyDensity = qs.DerivedQuantitySpecOfCharacter("electromagnetic energy density", ElectricFieldStrength.Times(ElectricFluxDensity), qs.QuantityCharacter.scalar);
pub const PoyntingVector = qs.DerivedQuantitySpec("poynting vector", ElectricFieldStrength.Times(MagneticFieldStrength)); // TODO verify is vector
pub const SourceVoltage = qs.ChildQuantitySpec("source voltage", Voltage);
pub const SourceTension = SourceVoltage;
pub const MagneticPotential = qs.ChildQuantitySpec("magnetic potential", base.ElectricCurrent); // TODO from mp-units what is a correct equation here?
pub const MagneticTension = qs.ChildQuantitySpecWithEquationOfCharacter("magnetic tension", base.ElectricCurrent, MagneticFieldStrength.Times(st.PositionVector), qs.QuantityCharacter.scalar);
pub const MagnetomotiveForce = qs.ChildQuantitySpecWithEquationOfCharacter("magnetomotive force", base.ElectricCurrent, MagneticFieldStrength.Times(st.PositionVector), qs.QuantityCharacter.scalar);
pub const NumberOfTurnsInAWinding = qs.ChildQuantitySpec("number of turns in a winding", qs.Dimensionless);
pub const Reluctance = qs.DerivedQuantitySpec("reluctance", MagneticTension.Div(MagneticFlux));
pub const Permeance = qs.DerivedQuantitySpec("permeance", Reluctance.Inverse());
pub const Inductance = qs.DerivedQuantitySpec("inductance", Protoflux.Div(base.ElectricCurrent));
pub const SelfInductance = Inductance;
pub const MutualInductance = qs.DerivedQuantitySpec("mutual inductance", Protoflux.Div(base.ElectricCurrent));
pub const CouplingFactor = qs.ChildQuantitySpecWithEquation("coupling factor", qs.Dimensionless, MutualInductance.DivEqn(SelfInductance.Pow(2).Sqrt()));
pub const LeakageFactor = qs.ChildQuantitySpecWithEquation("leakage factor", qs.Dimensionless, CouplingFactor.Pow(2));
pub const Conductivity = qs.DerivedQuantitySpecOfCharacter("conductivity", ElectricCurrentDensity.Div(ElectricFieldStrength), qs.QuantityCharacter.scalar);
pub const Resistivity = qs.DerivedQuantitySpec("resistivity", Conductivity.Inverse());
pub const ElectromagnetismPower = qs.ChildQuantitySpecWithEquation("electromagnetism power", mc.Power, Voltage.Times(base.ElectricCurrent)); // different name than in ISQ
pub const InstantaneousPower = ElectromagnetismPower;
pub const Resistance = qs.DerivedQuantitySpec("resistance", Voltage.Div(base.ElectricCurrent));
pub const Conductance = qs.DerivedQuantitySpec("conductance", Resistance.Inverse());
pub const PhaseDifference = qs.ChildQuantitySpec("phase difference", st.PhaseAngle);
pub const ElectricCurrentPhasor = qs.ChildQuantitySpecOfCharacter("electric current phasor", base.ElectricCurrent, qs.QuantityCharacter.complexScalar);
pub const VoltagePhasor = qs.ChildQuantitySpecOfCharacter("voltage phasor", Voltage, qs.QuantityCharacter.complexScalar);
pub const ElectricTensionPhasor = VoltagePhasor;
pub const Impedance = qs.DerivedQuantitySpec("impedance", VoltagePhasor.Div(ElectricCurrentPhasor)); // TODO verify is complex
pub const ComplexImpedance = Impedance; // TODO verify is complex
pub const ImpedanceOfVacuum = qs.DerivedQuantitySpec("impedance of vacuum", Impedance); // TODO verify is complex
pub const WaveImpedanceInVacuum = ImpedanceOfVacuum; // TODO verify is complex
pub const ResistanceToAlternatingCurrent = qs.ChildQuantitySpecOfCharacter(Impedance, qs.QuantityCharacter.scalar); // called resistance in the latest ISQ (we use the old name to avoid ambiguity)
pub const Reactance = qs.DerivedQuantitySpec("reactance", Impedance, qs.QuantityCharacter.scalar);
pub const ApparentImpedance = qs.DerivedQuantitySpec("apparent impedance", Impedance, qs.QuantityCharacter.scalar);
pub const Admittance = qs.DerivedQuantitySpec("admittance", Impedance.Inverse()); // TODO verify is complex
pub const ComplexAdmittance = Admittance; // TODO verify is complex
pub const AdmittanceOfVacuum = qs.ChildQuantitySpecWithEquation("admittance of vacuum", Admittance, ImpedanceOfVacuum.Inverse()); // TODO verify is complex
pub const ConductanceForAlternatingCurrent = qs.ChildQuantitySpecOfCharacter("conductance for alternating current", Conductance, qs.QuantityCharacter.scalar); // called conductance in the latest ISQ (we use the old name to avoid ambiguity)
pub const Susceptance = qs.ChildQuantitySpecOfCharacter("susceptance", Admittance, qs.QuantityCharacter.scalar);
pub const ApparentAdmittance = qs.ChildQuantitySpecOfCharacter("apparent admittance", Admittance, qs.QuantityCharacter.scalar);
pub const QualityFactor = qs.DerivedQuantitySpec("quality factor", qs.Dimensionless, Reactance.Div(Resistance));
pub const LossFactor = qs.ChildQuantitySpecWithEquation("loss factor", qs.Dimensionless, QualityFactor.Inverse());
pub const LossAngle = qs.ChildQuantitySpec("loss angle", si.AngularMeasure);
pub const ActivePower = qs.DerivedQuantitySpec("active power", mc.Power, si.Period.Inverse().TimesEqn(InstantaneousPower.Times(base.Time)));
pub const ComplexPower = qs.DerivedQuantitySpec("complex power", VoltagePhasor.Times(ElectricCurrentPhasor)); // complex // separate kind
pub const ApparentPower = qs.ChildQuantitySpecOfCharacter("apparent power", ComplexPower, qs.QuantityCharacter.scalar);
pub const PowerFactor = qs.ChildQuantitySpecWithEquation("power factor", qs.Dimensionless, ActivePower.Div(ApparentPower));
pub const ReactivePower = qs.DerivedQuantitySpec("reactive power", base.Mass.TimesEqn(base.Length.Pow(2)).DivEqn(base.Time.Pow(3))); // separate kind
/// TODO not sure if this works right, but it's defined as sqrt(ApparentPower^2 - ActivePower^2) in spec, and defined as sqrt(ApparentPower^2) in mp-units
pub const NonActivePower = qs.DerivedQuantitySpec("non active power", ApparentPower.Pow(2).Sqrt()); // separate kind
pub const ActiveEnergy = qs.DerivedQuantitySpec("active energy", InstantaneousPower.Times(base.Time));
