const qs = @import("../../lib/quantity_spec.zig");
const base = @import("base.zig");
const st = @import("space_and_time.zig");
const si = @import("si_quantities.zig");
// TODO include SI quantities?
// TODO include space and time?

pub const MassDensity = qs.DerivedQuantitySpec("mass density", base.Mass.Div(st.Volume));
pub const Density = MassDensity;
pub const SpecificVolume = qs.DerivedQuantitySpec("specific volume", MassDensity.Inverse());
// TODO how should VVV this VVV work?
pub const RelativeMassDensity = qs.DerivedQuantitySpec("relative mass density", MassDensity.Div(MassDensity));
pub const RelativeDensity = RelativeMassDensity;
pub const SurfaceMassDensity = qs.DerivedQuantitySpec("surface mass density", base.Mass.Div(si.Area));
pub const SurfaceDensity = SurfaceMassDensity;
pub const LinearMassDensity = qs.DerivedQuantitySpec("linear mass density", base.Mass.Div(base.Length));
pub const LinearDensity = LinearMassDensity;
pub const Momentum = qs.DerivedQuantitySpec("momentum", base.Mass.Times(st.Velocity)); // TODO make sure is vector
pub const Force = qs.DerivedQuantitySpec("force", base.Mass.Times(st.Acceleration)); // TODO make sure is vector
pub const Weight = qs.DerivedQuantitySpec("weight", Force, base.Mass.Times(st.AccelerationOfFreeFall)); // TODO make sure is vector  // differs from ISO 80000
pub const StaticFrictionForce = qs.ChildQuantitySpec("static friction force", Force); // TODO make sure is vector
pub const StaticFriction = StaticFrictionForce;
pub const KineticFrictionForce = qs.ChildQuantitySpec("kinetic friction force", Force); // TODO make sure is vector
pub const DynamicFrictionForce = KineticFrictionForce;
pub const RollingResistance = qs.ChildQuantitySpec("rolling resistance", Force); // TODO make sure is vector
pub const RollingDrag = RollingResistance;
pub const RollingFrictionForce = RollingResistance;
pub const DragForce = qs.ChildQuantitySpec("drag force", Force); // TODO make sure is vector
pub const Impulse = qs.DerivedQuantitySpec("impulse", Force.Times(base.Time)); // TODO make sure is vector
pub const AngularMomentum = qs.DerivedQuantitySpec("angular momentum", st.PositionVector.Times(Momentum)); // TODO make sure is vector
pub const MomentOfInertia = qs.DerivedQuantitySpecOfCharacter("MomentOfInertia", AngularMomentum.Div(st.AngularVelocity), qs.QuantityCharacter.tensor);
pub const MomentOfForce = qs.DerivedQuantitySpec("moment of force", st.PositionVector.Times(Force)); // TODO make sure is vector
pub const Torque = qs.ChildQuantitySpecOfCharacter("torque", MomentOfForce, qs.QuantityCharacter.scalar);
pub const AngularImpulse = qs.DerivedQuantitySpec("angular impulse", MomentOfForce.Times(base.Time)); // TODO make sure is vector
pub const Pressure = qs.DerivedQuantitySpecOfCharacter("pressure", Force.Div(si.Area), qs.QuantityCharacter.scalar);
pub const GaugePressure = qs.ChildQuantitySpec("gauge pressure", Pressure);
pub const Stress = qs.ChildQuantitySpecOfCharacter("stress", Pressure, qs.QuantityCharacter.tensor);
pub const NormalStress = qs.ChildQuantitySpecOfCharacter("normal stress", Pressure, qs.QuantityCharacter.scalar);
pub const ShearStress = qs.ChildQuantitySpecOfCharacter("shear stress", Pressure, qs.QuantityCharacter.scalar);
pub const Strain = qs.ChildQuantitySpecOfCharacter("strain", qs.Dimensionless, qs.QuantityCharacter.tensor);
pub const RelativeLinearStrain = qs.DerivedQuantitySpec("relative linear strain", base.Length.Div(base.Length));
pub const ShearStrain = qs.ChildQuantitySpecWithEquationOfCharacter("shear strain", qs.Dimensionless, st.Displacement.Div(st.Thickness), qs.QuantityCharacter.scalar);
pub const RelativeVolumeStrain = qs.DerivedQuantitySpec("relative volume strain", st.Volume.Div(st.Volume));
pub const PoissonNumber = qs.ChildQuantitySpecWithEquation("poisson number", qs.Dimensionless, si.Width / base.Length);
pub const ModulusOfElasticity = qs.DerivedQuantitySpec("modulus of elasticity", NormalStress.Div(RelativeLinearStrain));
pub const YoungModulus = ModulusOfElasticity;
pub const ModulusOfRigidity = qs.DerivedQuantitySpec("modulus of rigidity", ShearStress.Div(ShearStrain));
pub const ShearModulus = ModulusOfRigidity;
pub const ModulusOfCompression = qs.DerivedQuantitySpec("modulus of compression", Pressure.Div(RelativeVolumeStrain));
pub const BulkModulus = ModulusOfCompression;
pub const Compressibility = qs.DerivedQuantitySpec("compressibility", st.Volume.Inverse().Times(st.Volume.Div(Pressure)));
pub const SecondAxialMomentOfArea = qs.DerivedQuantitySpec("second axial moment of area", st.RadialDistance.Pow(2).Times(si.Area));
pub const SecondPolarMomentOfArea = qs.DerivedQuantitySpec("second polar moment of area", st.RadialDistance.Pow(2).Times(si.Area));
pub const SectionModulus = qs.DerivedQuantitySpec("section modulus", SecondAxialMomentOfArea.Div(st.RadialDistance));
pub const StaticFrictionCoefficient = qs.ChildQuantitySpecWithEquationOfCharacter("static friction coefficient", qs.Dimensionless, StaticFrictionForce.Div(Force), qs.QuantityCharacter.scalar);
pub const StaticFrictionFactor = StaticFrictionCoefficient;
pub const CoefficientOfStaticFriction = StaticFrictionCoefficient;
pub const KineticFrictionFactor = qs.ChildQuantitySpecWithEquationOfCharacter("kinetic friction factor", qs.Dimensionless, KineticFrictionForce.Div(Force), qs.QuantityCharacter.scalar);
pub const DynamicFrictionFactor = KineticFrictionFactor;
pub const RollingResistanceFactor = qs.DerivedQuantitySpecOfCharacter("rolling resistance factor", Force.Div(Force), qs.QuantityCharacter.scalar);
pub const DragCoefficient = qs.ChildQuantitySpecWithEquationOfCharacter("drag coefficient", qs.Dimensionless, DragForce.Div(MassDensity.Times(st.Speed.Pow(2)).Times(si.Area)), qs.QuantityCharacter.scalar);
pub const DragFactor = DragCoefficient;
pub const DynamicViscosity = qs.DerivedQuantitySpecOfCharacter("dynamic viscosity", ShearStress.Times(base.Length).Div(st.Velocity), qs.QuantityCharacter.scalar);
pub const KinematicViscosity = qs.DerivedQuantitySpec("kinematic viscosity", DynamicViscosity.Div(MassDensity));
pub const SurfaceTension = qs.DerivedQuantitySpecOfCharacter("surface tension", Force.Div(base.Length), qs.QuantityCharacter.scalar); // TODO (from mp-units) what is a correct equation here?
pub const Power = qs.DerivedQuantitySpec("power", base.Mass.Times(base.Length.Pow(2)).Div(base.Time.Pow(3))); // not in ISO 80000
pub const MechanicalPower = qs.ChildQuantitySpecWithEquationOfCharacter("mechanical power", Power, Force.Times(st.Velocity), qs.QuantityCharacter.scalar);
pub const MechanicalEnergy = qs.ChildQuantitySpec("mechanical energy", si.Energy); // differs from ISO 80000
pub const PotentialEnergy = qs.ChildQuantitySpec("potential energy", MechanicalEnergy); // differs from ISO 80000
pub const KineticEnergy = qs.ChildQuantitySpecWithEquation("kinetic energy", MechanicalEnergy, base.Mass.Times(st.Speed.Pow(2))); // differs from ISO 80000
pub const MechanicalWork = qs.DerivedQuantitySpecOfCharacter("mechanical work", Force.Times(st.Displacement), qs.QuantityCharacter.scalar);
pub const Work = MechanicalWork;
pub const MechanicalEfficiency = qs.DerivedQuantitySpec("mechanical efficiency", MechanicalPower.Div(MechanicalPower));
pub const MassFlow = qs.DerivedQuantitySpec("mass flow", MassDensity.Times(st.Velocity)); // TODO should be vector
pub const MassFlowRate = qs.DerivedQuantitySpecOfCharacter("mass flow rate", MassFlow.Times(si.Area), qs.QuantityCharacter.scalar);
pub const MassChangeRate = qs.DerivedQuantitySpec("mass change rate", base.Mass.Div(base.Time));
pub const VolumeFlowRate = qs.DerivedQuantitySpecOfCharacter("volume flow rate", st.Velocity.Times(si.Area), qs.QuantityCharacter.scalar);
pub const Action = qs.DerivedQuantitySpec("action", si.Energy.Times(base.Time));
