const qs = @import("../../lib/quantity_spec.zig");
const base = @import("base.zig");
const mc = @import("mechanics.zig");
const si = @import("si_quantities.zig");
const st = @import("space_and_time.zig");

pub const CelsiusTemperature = qs.DerivedQuantitySpec("Celsius_temperature", base.ThermodynamicTemperature); // TODO should we account for T0 here?
pub const LinearExpansionCoefficient = qs.DerivedQuantitySpec("linear_expansion_coefficient", base.Length.Inverse() * (base.Length / base.ThermodynamicTemperature));
pub const CubicExpansionCoefficient = qs.DerivedQuantitySpec("cubic_expansion_coefficient", st.Volume.Inverse() * (st.Volume / base.ThermodynamicTemperature));
pub const RelativePressureCoefficient = qs.DerivedQuantitySpec("relative_pressure_coefficient", mc.Pressure.Inverse() * (mc.Pressure / base.ThermodynamicTemperature));
pub const PressureCoefficient = qs.DerivedQuantitySpec("pressure_coefficient", mc.Pressure / base.ThermodynamicTemperature);
pub const IsothermalCompressibility = qs.DerivedQuantitySpec("isothermal_compressibility", st.Volume.Inverse() * (st.Volume / mc.Pressure)); // TODO how to handle "negative" part
pub const IsentropicCompressibility = qs.DerivedQuantitySpec("isentropic_compressibility", st.Volume.Inverse() * (st.Volume / mc.Pressure)); // TODO how to handle "negative" part
// energy definition moved to mechanics
pub const Heat = qs.DerivedQuantitySpec("heat", si.Energy);
pub const AmountOfHeat = Heat;
pub const LatentHeat = qs.DerivedQuantitySpec("latent_heat", Heat); // TODO what is a correct equation here?
pub const HeatFlowRate = qs.DerivedQuantitySpec("heat_flow_rate", Heat / base.Time);
pub const DensityOfHeatFlowRate = qs.DerivedQuantitySpec("density_of_heat_flow_rate", HeatFlowRate / si.Area);
pub const ThermalConductivity = qs.DerivedQuantitySpec("thermal_conductivity", DensityOfHeatFlowRate * (base.Length / base.ThermodynamicTemperature));
pub const CoefficientOfHeatTransfer = qs.DerivedQuantitySpec("coefficient_of_heat_transfer", DensityOfHeatFlowRate / base.ThermodynamicTemperature);
pub const SurfaceCoefficientOfHeatTransfer = qs.DerivedQuantitySpec("surface_coefficient_of_heat_transfer", DensityOfHeatFlowRate / base.ThermodynamicTemperature);
pub const ThermalInsulance = qs.DerivedQuantitySpec("thermal_insulance", CoefficientOfHeatTransfer.Inverse());
pub const CoefficientOfThermalInsulance = ThermalInsulance;
pub const ThermalResistance = qs.DerivedQuantitySpec("thermal_resistance", base.ThermodynamicTemperature / HeatFlowRate);
pub const ThermalConductance = qs.DerivedQuantitySpec("thermal_conductance", ThermalResistance.Inverse());
pub const HeatCapacity = qs.DerivedQuantitySpec("heat_capacity", Heat / base.ThermodynamicTemperature);
pub const SpecificHeatCapacity = qs.DerivedQuantitySpec("specific_heat_capacity", HeatCapacity / base.Mass);
pub const SpecificHeatCapacityAtConstantPressure = qs.DerivedQuantitySpec("specific_heat_capacity_at_constant_pressure", SpecificHeatCapacity);
pub const SpecificHeatCapacityAtConstantVolume = qs.DerivedQuantitySpec("specific_heat_capacity_at_constant_volume", SpecificHeatCapacity);
pub const SpecificHeatCapacityAtSaturatedVapourPressure = qs.DerivedQuantitySpec("specific_heat_capacity_at_saturated_vapour_pressure", SpecificHeatCapacity);
pub const ThermalDiffusivity = qs.DerivedQuantitySpec("thermal_diffusivity", ThermalConductivity / (mc.MassDensity * SpecificHeatCapacityAtConstantPressure));
pub const RatioOfSpecificHeatCapacities = qs.DerivedQuantitySpec("ratio_of_specific_heat_capacities", qs.Dimensionless, SpecificHeatCapacityAtConstantPressure / SpecificHeatCapacityAtConstantVolume);
pub const IsentropicExponent = qs.DerivedQuantitySpec("isentropic_exponent", st.Volume / mc.Pressure * (mc.Pressure / st.Volume)); // TODO how to handle "negative" part
pub const IsentropicExpansionFactor = IsentropicExponent;
pub const Entropy = qs.DerivedQuantitySpec("entropy", mc.KineticEnergy / base.ThermodynamicTemperature);
pub const SpecificEntropy = qs.DerivedQuantitySpec("specific_entropy", Entropy / base.Mass);
pub const Enthalpy = qs.DerivedQuantitySpec("enthalpy", si.Energy); // differs from ISO 80000
pub const InternalEnergy = qs.DerivedQuantitySpec("internal_energy", Enthalpy); // differs from ISO 80000
pub const ThermodynamicEnergy = InternalEnergy;
pub const HelmholtzEnergy = qs.DerivedQuantitySpec("Helmholtz_energy", InternalEnergy);
pub const HelmholtzFunction = HelmholtzEnergy;
pub const GibbsEnergy = qs.DerivedQuantitySpec("Gibbs_energy", Enthalpy);
pub const GibbsFunction = GibbsEnergy;
pub const SpecificEnergy = qs.DerivedQuantitySpec("specific_energy", si.Energy / base.Mass);
pub const SpecificInternalEnergy = qs.DerivedQuantitySpec("specific_internal_energy", InternalEnergy / base.Mass);
pub const SpecificThermodynamicEnergy = SpecificInternalEnergy;
pub const SpecificEnthalpy = qs.DerivedQuantitySpec("specific_enthalpy", Enthalpy / base.Mass);
pub const SpecificHelmholtzEnergy = qs.DerivedQuantitySpec("specific_Helmholtz_energy", HelmholtzEnergy / base.Mass);
pub const SpecificHelmholtzFunction = SpecificHelmholtzEnergy;
pub const SpecificGibbsEnergy = qs.DerivedQuantitySpec("specific_Gibbs_energy", GibbsEnergy / base.Mass);
pub const SpecificGibbsFunction = SpecificGibbsEnergy;
pub const MassieuFunction = qs.DerivedQuantitySpec("Massieu_function", HelmholtzEnergy / base.ThermodynamicTemperature); // TODO how to handle "negative" part
pub const PlanckFunction = qs.DerivedQuantitySpec("Planck_function", GibbsEnergy / base.ThermodynamicTemperature); // TODO how to handle "negative" part
pub const JouleThomsonCoefficient = qs.DerivedQuantitySpec("Joule_Thomson_coefficient", base.ThermodynamicTemperature / mc.Pressure);
pub const ThermodynamicEfficiency = qs.DerivedQuantitySpec("thermodynamic_efficiency", qs.Dimensionless, mc.Work / Heat);
pub const MaximumEfficiency = qs.DerivedQuantitySpec("maximum_efficiency", base.ThermodynamicTemperature / base.ThermodynamicTemperature);
pub const SpecificGasConstant = qs.DerivedQuantitySpec("specific_gas_constant", Entropy / base.Mass);
pub const MassConcentrationOfWater = qs.DerivedQuantitySpec("mass_concentration_of_water", base.Mass / st.Volume);
pub const MassConcentrationOfWaterVapour = qs.DerivedQuantitySpec("mass_concentration_of_water_vapour", base.Mass / st.Volume);
pub const MassRatioOfWaterToDryMatter = qs.DerivedQuantitySpec("mass_ratio_of_water_to_dry_matter", base.Mass / base.Mass);
pub const MassRatioOfWaterVapourToDryGas = qs.DerivedQuantitySpec("mass_ratio_of_water_vapour_to_dry_gas", base.Mass / base.Mass);
pub const MassFractionOfWater = qs.DerivedQuantitySpec("mass_fraction_of_water", MassRatioOfWaterToDryMatter / MassRatioOfWaterToDryMatter);
pub const MassFractionOfDryMatter = qs.DerivedQuantitySpec("mass_fraction_of_dry_matter", MassFractionOfWater);
pub const RelativeHumidity = qs.DerivedQuantitySpec("relative_humidity", mc.Pressure / mc.Pressure);
pub const RelativeMassConcentrationOfVapour = qs.DerivedQuantitySpec("relative_mass_concentration_of_vapour", MassConcentrationOfWaterVapour / MassConcentrationOfWaterVapour);
pub const RelativeMassRatioOfVapour = qs.DerivedQuantitySpec("relative_mass_ratio_of_vapour", MassRatioOfWaterVapourToDryGas / MassRatioOfWaterVapourToDryGas);
pub const DewPointTemperature = qs.DerivedQuantitySpec("dew_point_temperature", base.ThermodynamicTemperature);
